object Versions {
    const val compose = "1.1.1"
    const val activityCompose = "1.4.0"
    const val lifecycleViewModelCompose = "2.4.1"
    const val kotlin = "1.6.10"
    const val kotlinxSerialization = "1.3.2"
    const val ktlint = "0.45.2"
    const val coroutines = "1.6.1"
    const val koin = "3.2.0-beta-1"
    const val fragment = "1.3.5"
    const val lifecycle = "2.4.1"
    const val core = "1.7.0"
    const val jUnit = "4.12"
    const val androidxTest = "1.4.0"
    const val retrofit = "2.9.0"
    const val nav = "2.4.2"
    const val room = "2.4.2"
    const val splash = "1.0.0-beta02"
    const val material = "1.6.0"
    const val appCompat = "1.4.1"
    const val constraintLayout = "2.0.4"
    const val recyclerView = "1.2.1"
    const val recyclerViewSelection = "1.2.0-alpha01"
    const val retrofitKotlinxSerializationConverter = "0.8.0"
    const val retrofitLoggingInterceptor = "4.9.3"
    const val timber = "5.0.1"
    const val chucker = "3.5.2"
}